CFLAGS=-O3 -fopenmp -finline -std=c++11  

main: 

	g++ $(CFLAGS) main.cpp generator/DataGenerator.cpp generator/Gaussian.cpp generator/ValueGenerator.cpp generator/VectorCommon.cpp -o main 


clean:

	rm main

